spring.application.name=guia-despacho
server.port=8080

# Configuracion AWS S3
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.sessionToken=${AWS_SESSION_TOKEN:}
aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket=${AWS_S3_BUCKET}

# Configuracion EFS (montaje local o en EC2)
efs.mount.path=${EFS_MOUNT_PATH:/mnt/efs}

# Configuracion para subida de archivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
